name: Expo - Publish on main

on:
  push:
    branches: [ "main" ] # roda após merges que entram em main

jobs:
  eas-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      # autentica no Expo usando o token salvo em secrets
      - name: Login to Expo
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Publish EAS Update to develop channel
        run: npx eas update --channel develop --non-interactive --message "CI: $GITHUB_SHA"

      # opcional: mostra a URL de updates do seu projeto/canal no log
      - name: Show update URL hint
        run: |
          echo "Abra: https://expo.dev/accounts/${{ env.EXPO_OWNER }}/projects/${{ env.EXPO_SLUG }}/updates?channel=develop"
        env:
          EXPO_OWNER: gledsonsantos        # mantenha em sync com app.json/app.config
          EXPO_SLUG: pessoal-coach
